### ISSUE TITLE
Doesn't work with horizontal bar chart

### ISSUE THREAD

**Issue by slominskir** [thgreasi/growraf#3]
I didn't see any way to use this for a horizontal bar chart.

**Comment by thgreasi** [comment]
Yes, that's true. I never had this use case so I didn't invest any time to this till now.
Thanks for the report.
Will investigate in the next weekend.

If in the meantime you have reached to a working solution, I would be happy to review any PR's.

**Comment by thgreasi** [comment]
Resolved in [v0.5.0](https://github.com/thgreasi/growraf/releases/tag/v0.5.0) by 9a5ad2af9c888e8c829a79f6e42b2ee4108d2c78.
Take a look at the [Horizontal Bars example](http://thgreasi.github.io/growraf/horizontal.html).

**Comment by thgreasi** [comment]
@slominskir does it work for you?

**Comment by slominskir** [comment]
Works great.  Thanks.
