### ISSUE TITLE
Grey bar inside animated bar

### ISSUE THREAD

**Issue by riklaunim** [thgreasi/growraf#4]
After hooking up animations for my horizontal bar graphs I get grey bars inside graph bars  when having `fillColor: { colors: [ { opacity: 0.8 }, { opacity: 0.1 } ] },` for bars. Setting fixed color for fillColor kills that grey thing, but also prevents custom colors which I have - per data set or per value arithmetics. So how to remove that inner grey bar without limiting features?

![chart](https://cloud.githubusercontent.com/assets/1822699/6443705/f8501a5c-c0f8-11e4-8244-a180ab84a75e.png)

**Comment by thgreasi** [comment]
As far as I can remember from the source code, we are not adding any grey
bars intentionally.
Can you provide a codepen/jsgfiddle example? If yes, then I can start
investigating it early as tomorrow morning.

**Comment by riklaunim** [comment]
will try to provide it.

**Comment by thgreasi** [comment]
(Here)[http://codepen.io/thgreasi/pen/myjVVX] is an example with gradients & growraf 
and (here)[http://codepen.io/thgreasi/pen/wBxMMY] is the same example without loading the growraf lib at all. On first sight I cann't spot any difference, so the grey boxes might not be generated by growraf.

Please feel free to re-open this issue, in case you can provide some examples of your use case showcasing the contrary.

**Comment by riklaunim** [comment]
It was somehove caused by "fontcolor" in valuesLabels. When I removed it the bars were ok.
